webhook:
  secret: 1221324354554354354353
github:
  appId: 1968
  privateKey: /secrets/private-key
defaults:
  labels:
    approved: "approved"
    wip:
    - "status/wip"
    - "wip"
    - "do not merge"
  wipPatterns:
  - "do not merge"
  - "wip"
repos:
  syndesis:
    labels:
      reviewRequested: "status/review-requested"
      approved: "status/approved"
      newIssues:
      - "notif/triage"
  pure-bot-sandbox:
    disabled: true
    board:
      zenhub_token: "<zenhub token>"
      github_repo: "<github repository id>"
      columns:
        - name: "backlog"
          id: "5b33b25ab0388a502999f52b"
        - name: "progress"
          id: "5b33b25ab0388a502999f52c"
        - name: "review"
          id: "5b33b25ab0388a502999f52d"
        - name: "closed"
          id: "5b33b25ab0388a502999f52e"