webhook:
  secret: 1221324354554354354353
github:
  appId: 1968
  privateKey: /secrets/private-key
defaults:
  labels:
    approved: "approved"
    wip:
    - "status/wip"
    - "wip"
    - "do not merge"
  wipPatterns:
  - "do not merge"
  - "wip"
repos:
  syndesis:
    labels:
      reviewRequested: "status/review-requested"
      approved: "status/approved"
      newIssues:
      - "notif/triage"
  pure-bot-sandbox:
    disabled: true
    board:
      zenhub_token: "<zenhub token>"
      github_repo: "<github repository id>"
     columns:
            - name: "backlog"
              id: "5b33b25ab0388a502999f52b"
              events:
                - "issues_unassigned"
                - "issues_opened"
                - "issues_reopened"
            - name: "progress"
              id: "5b33b25ab0388a502999f52c"
              events:
                - "issues_assigned"
                - "pull_request_closed"
            - name: "review"
              id: "5b33b25ab0388a502999f52d"
              events:
                - "pull_request_opened"
                - "pull_request_reopened"
            - name: "closed"
              id: "5b33b25ab0388a502999f52e"
              events:
                - "issues_closed"
