webhook:
  secret: 1221324354554354354353
github:
  appId: 1968
  privateKey: /secrets/private-key
defaults:
  labels:
    approved: "approved"
    wip:
    - "status/wip"
    - "wip"
    - "do not merge"
  wipPatterns:
  - "do not merge"
  - "wip"
repos:
  syndesis:
    labels:
      reviewRequested: "status/review-requested"
      approved: "status/approved"
      newIssues:
      - "notif/triage"
pure-bot-sandbox:
    disabled: true
    board:
      zenhub_token: "<TOKEN>"
      github_repo: "<REPO>"
      columns:
        - name: "Inbox"
          id: "<ID>"
          isInbox: true
          events:
            - "issues_demilestoned"
            - "issues_opened"
        - name: "Backlog"
          id: "<ID>"
          events:
            - "issues_reopened"
            - "issues_milestoned"
        - name: "Review"
          id: "<ID>"
          events:
            - "pull_request_opened"
            - "pull_request_reopened"
        - name: "Done"
          id: "<ID>"
          postMergePipeline: true
