# Copyright 2017 The Syndesis Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

job_defaults: &job_defaults
  working_directory: /go/src/github.com/syndesisio/pure-bot

  docker:
  - image: golang:1.9.2

  environment: &env_defaults
  - CGO_ENABLED: "0"

version: 2

jobs:
  checkout_code:
    <<: *job_defaults

    steps:
      - checkout

      - run: git fetch --tags

      - save_cache:
          key: code-repo-{{ .Environment.CIRCLE_SHA1 }}-{{ .Environment.CIRCLE_TAG }}
          paths:
          - /go/src/github.com/syndesisio/pure-bot

  vendor_dependencies:
    <<: *job_defaults

    steps:
      - restore_cache:
          keys:
          - code-repo-{{ .Environment.CIRCLE_SHA1 }}-{{ .Environment.CIRCLE_TAG }}

      - run:
          name: Update dependencies
          command: |
            command -v dep >/dev/null 2>&1 || go get github.com/golang/dep/cmd/dep
            dep ensure -v

      - save_cache:
          key: vendor-{{ checksum "Gopkg.lock" }}
          paths:
          - /go/src/github.com/syndesisio/pure-bot/vendor

  build:
    <<: *job_defaults

    steps:
      - restore_cache:
          keys:
          - code-repo-{{ .Environment.CIRCLE_SHA1 }}-{{ .Environment.CIRCLE_TAG }}

      - restore_cache:
          keys:
          - vendor-{{ checksum "Gopkg.lock" }}

      - run:
          name: Build binary

          command: |
            ROOT_PKG=$(go list .)
            VERSION=$(git describe --match 'v[0-9]*' --dirty --always)
            BUILD_DATE=$(date -u)

            go build -v                                                                                                           \
                -installsuffix "static"                                                                                           \
                -ldflags "-X ${ROOT_PKG}/pkg/version.AppVersion=${VERSION} -X '${ROOT_PKG}/pkg/version.BuildDate=${BUILD_DATE}'"  \
                -o pure-bot \
                .

      - persist_to_workspace:
          root: .
          paths:
          - pure-bot

      - store_artifacts:
          path: ./pure-bot
          destination: pure-bot

  test:
    <<: *job_defaults

    steps:
      - restore_cache:
          keys:
          - code-repo-{{ .Environment.CIRCLE_SHA1 }}-{{ .Environment.CIRCLE_TAG }}

      - restore_cache:
          keys:
          - vendor-{{ checksum "Gopkg.lock" }}

      - run:
          name: Run tests
          command: |
            TARGETS=$(go list ./... | grep -v /vendor/)
            go test -v -cover -installsuffix "static" ${TARGETS}

      - run:
          name: Check gofmt
          command: |
            ERRS=$(find "$@" -type f ! -path '*/vendor/*' -name \*.go | xargs gofmt -l 2>&1 || true)
            if [ -n "${ERRS}" ]; then
                echo "The following files need to be gofmt'ed:"
                echo
                for e in ${ERRS}; do
                    echo "    $e"
                done
                exit 1
            fi

      - run:
          name: Run go vet
          command: |
            TARGETS=$(go list ./... | grep -v /vendor/)
            ERRS=$(go vet ${TARGETS} 2>&1 || true)
            echo "There are go vet errors:"
            echo
            if [ -n "${ERRS}" ]; then
                echo "${ERRS}"
                exit 1
            fi

  build_docker:
    <<: *job_defaults

    docker:
    - image: docker:17.09.0-ce-git

    steps:
      - restore_cache:
          keys:
          - code-repo-{{ .Environment.CIRCLE_SHA1 }}-{{ .Environment.CIRCLE_TAG }}

      - setup_remote_docker:
          version: 17.09.0-ce

      - attach_workspace:
          at: .

      - run:
          name: Build Docker image
          command: |
            docker build \
              -f .circleci/Dockerfile \
              -t syndesis/pure-bot:${CIRCLE_SHA1} .

      - run:
          name: Export Docker image
          command: |
            docker save -o ./pure-bot-docker.tar syndesis/pure-bot:${CIRCLE_SHA1}

      - persist_to_workspace:
          root: .
          paths:
          - pure-bot-docker.tar

      - store_artifacts:
          path: ./pure-bot-docker.tar
          destination: pure-bot-docker.tar

  push_docker:
    <<: *job_defaults

    docker:
    - image: docker:17.09.0-ce-git

    steps:
      - setup_remote_docker:
          version: 17.09.0-ce

      - attach_workspace:
          at: .

      - run:
          name: Push Docker image
          command: |
            if [ "${CIRCLE_PROJECT_USERNAME}" != "syndesisio" ]; then
              echo "Skipping - this is not in origin repository"
              exit 0
            fi

            if [ -z "${DOCKER_LOGIN}" ] || [ -z "${DOCKER_PASSWORD}" ]; then
              echo "Missing Docker login information!!!"
              exit 1
            fi

            docker load -q -i ./pure-bot-docker.tar

            DOCKER_TAG=${CIRCLE_TAG:-latest}

            docker tag syndesis/pure-bot:${CIRCLE_SHA1} syndesis/pure-bot:${DOCKER_TAG}

            docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}

            docker push syndesis/pure-bot:${DOCKER_TAG}

  openshift_deploy:
    <<: *job_defaults

    docker:
    - image: openshift/origin:v3.6.1

    steps:
      - run:
          name: Check prerequisites
          command: |
            if [ "${CIRCLE_PROJECT_USERNAME}" != "syndesisio" ] || [ -z "${CIRCLE_TAG}"]; then
              echo "This should only run for tags in origin repository"
              exit 1
            fi

            if [ -z "${OPENSHIFT_SERVER}"] || [ -z "${OPENSHIFT_PROJECT}"] || [ -z "${OPENSHIFT_TOKEN}"]; then
              echo "Missing OpenShift login environment variables"
              exit 1
            fi

      - run:
          name: OpenShift login
          command: openshift cli login ${OPENSHIFT_SERVER} --token=${OPENSHIFT_TOKEN}

      - run:
          name: Change OpenShift project
          command: openshift cli project ${OPENSHIFT_PROJECT}

      - run:
          name: Tag OpenShift image stream
          command: openshift cli tag --source=docker syndesis/pure-bot:${CIRCLE_TAG} pure-bot:deploy

      - run:
          name: Import latest image to OpenShift image stream
          command: openshift cli import-image pure-bot:deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
    - checkout_code:
        filters:
          tags:
            only:
              /v[0-9]+(\.[0-9]+)*/
    - vendor_dependencies:
        requires:
        - checkout_code
        filters:
          tags:
            only:
              /v[0-9]+(\.[0-9]+)*/
    - build:
        requires:
        - vendor_dependencies
        filters:
          tags:
            only:
              /v[0-9]+(\.[0-9]+)*/
    - test:
        requires:
        - vendor_dependencies
        filters:
          tags:
            only:
              /v[0-9]+(\.[0-9]+)*/
    - build_docker:
        requires:
        - build
        - test
        filters:
          tags:
            only:
              /v[0-9]+(\.[0-9]+)*/
    - push_docker:
        requires:
        - build_docker
        filters:
          branches:
            only: master
          tags:
            only:
              /v[0-9]+(\.[0-9]+)*/
    - openshift_deploy:
        requires:
        - push_docker
        filters:
          branches:
            ignore: /.*/
          tags:
            only:
              /v[0-9]+(\.[0-9]+)*/
